# Robin Kelley and Malcolm x All those great nouns
[
"ide'
 'africa'
 'cuba'
 'progressive movements'
 'cesaire'
 'fanon'
 u"'s predictions"
 'colonial language'
 'cesaire critiques'
 'formal sense'
 'colonial state'
 'old colonial state'
 'primary difference'
 'black faces'
 'new ruling class-the class'
 'fanon'
 'colonial masters'
 'new jack u.s.'
 'corporate rulers'
 'stalinists'
 'colonial discourse'
 'cesaire'
 'true radicals'
 'postcolonial theoty'
 'official apparatus'
 'cultural links'
 'colonial domination'
 'discourse'
 'political economy'
 'colonial domination'
 'whole way'
 'european terms'
 'discourse'
 u"master class 's ideology"
 'fanon'
 'cesaire'
 'europe'
 u"'s footsteps"
 'ancient way'
 'new direction altogether'
 'cesaire'
 'martinique'
 'fort-de.france'
 'brief pages'
 'old political parties'
 'labor exploitation'
 'different way'
 'discourse'
 'road map'
 'cesaire'
 'own miraculous weapons'
 'tropiques'
 'vichy'
 'european culture'
 'france'
 'native land'
 'revolutionary graffiti'
 'bold strokes'
 'great texts'
 'civilization'
 'hand grenade'
 'new history'
 'discourse'
 'dead docu.ment'
 'dead order'
 'different way'
 'cesaire'
 'lautn'
 u"amont 's"
 'chants'
 'maldoror'
 'can.nibalistic nature'
 'poetic knowledge'
 'discourse'
 'new insights'
 'postcolonial predicament'
 'old colonial order'
 'malcolm x'
 'ballot'
 'bullet'
 'speech'
 'april'
 'malcolm x'
 'prominent members'
 'civil rights movement'
 'cory'
 'methodist church'
 'cleveland'
 'ohio'
 'april'
 'black populace'
 'important time'
 'malcolm x'
 u"'s life"
 'nation'
 'islam'
 'negro revolt'
 'humble way'
 'democrat'
 'republican'
 'hunkies'
 'polacks'
 'italian refugees'
 'europe'
 'well'
 'america'
 u"n't need"
 u"n't need"
 'washington'
 'd.c.'
 'civil-rights legislation'
 'polack'
 'black people'
 'americanism'
 'black people'
 'i.'
 'american dream system'
 'america'
 'american dream'
 'american nightmare'
 'new friends'
 'new allies'
 'civil-rights struggle'
 'human rights'
 'whenever'
 'civil-rights struggle'
 'uncle sam'
 'outside world'
 'civil-rights struggle'
 'civil rights'
 'domestic affairs'
 'african brothers'
 'asian brothers'
 'latin-american'
 'domestic affairs'
 'civil rights'
 'uncle sam'
 'human rights'
 'human rights'
 'africa'
 'hungary'
 'asia'
 'america'
 'negro'
 'human rights'
 'civil rights'
 'civil-rights tree'
 'human-rights tree'
 'civil-rights struggle'
 'human rights'
 'black man'
 'general assembly'
 'uncle sam'
 'world court'
 'human rights'
 'civil rights'
 'civil rights'
 'civil rights means'
 'uncle sam'
 'human rights'
 'human rights'
 'world court'
 'uncle sam'
 u"'s hands"
 'black man'
 u"earth 's number-one hypocrite"
 'free world'
 'free world'
 'shall overcome'
 'expand'
 'civil-rights struggle'
 'human rights'
 'african brothers'
 'latin-american'
 'chinamen'
 'washington'
 'd.c.'
 'political chicanery'
 'america'
 'tin soldier'
 'uncle sam'
 'know\ufffd\ufffd\ufffdi disagree'
 'lomax'
 'poor nations'
 'poor nations'
 'rich nations'
 'nation\ufffd\ufffd\ufffdone vote'
 'equal vote'
 'asia'
 'africa'
 'darker parts'
 'sam'
 'russia'
 'right'
 'african-americans\ufffd\ufffd\ufffdthat'
 'america'
 'africans'
 'africans'
 'negro'
 'africans'
 u"n't catch hell"
 'civil-rights bills'
 'africans'
 'negro'
 'hoogagagooba'
 u"'ll show"
 'white man'
 'silly man'
 'atlanta'
 'white restaurant'
 'negro'
 'nigger dare'
 'muslim mosque'
 'york'
 'muslims'
 'islam'
 u"n't mix"
 'civil activities\ufffd\ufffd\ufffdnot'
 'religious services'
 'muslims'
 'political action'
 'economic action'
 'civic action'
 'social evils'
 'political philosophy'
 'black nationalism'
 'black man'
 'own community'
 'black man'
 'black community'
 'political philosophy'
 'black nationalism'
 'christian church'
 'naacp'
 'core'
 'sncc'
 '[ student'
 'nonviolent coordinating'
 'committee ] meetings'
 'muslim'
 'black'
 'shall overcome'
 'economic philosophy'
 'black nationalism'
 'white people'
 'white people'
 'white man'
 u"black man ca n't"
 'white community'
 'white man'
 'black community'
 'black nationalism involves'
 're-education program'
 'black community'
 'slum area'
 'white man'
 'economic philosophy'
 'black nationalism'
 'civic organization'
 'fraternal order'
 u"'s time"
 'own community'
 'own kind'
 'gain control'
 'own community'
 'social philosophy'
 'black nationalism'
 'drug addiction'
 'moral fiber'
 'own society'
 'own social circles'
 u"wo n't"
 'social circle'
 'great controversy'
 u"'s time"
 'article'
 'constitutional amendments'
 'white folks'
 'white man'
 'black man buying rifles'
 'white man'
 'malcolm'
 'uncle tom'
 'amen'
 'tom'
 'rifle clubs'
 'defense budget'
 u"ca n't begrudge"
 'medals'
 'big\ufffd\ufffd\ufffdany time'
 'cold blood'
 'white man'
 u"ca n't"
 'eichmann'
 'argentina'
 'american soldiers'
 u"'s business way"
 'vietnam'
 'cuba'
 'free elections\ufffd\ufffd\ufffdthis'
 'old cracker'
 'free elections'
 'own country'
 'negro'
 'cracker senator'
 'black people'
 'washington'
 'shall overcome'
 'white friends'
 'round-trip tickets'
 'one-way tickets'
 'non-violent army'
 'black nationalists'
 'lyndon b. johnson'
 'democratic party'
 'civil rights'
 'moral stand\ufffd\ufffd\ufffdright'
 'election time'
 'thank']
['discourse on colonialism aime cesaire translated'
 'joan pinkham'
 'poetics of anticolonialism'
 'robin d. g. kelley'
 'introduction'
 'poetics of anticolonialism robin d. g. kelley aime cesaire'
 'discourse'
 'colonialism'
 'world manifesto'
 'old order bereft'
 'accompany manifestos'
 'discourse'
 'revolutionary ca.dences'
 'marx'
 'engels'
 'discours'
 'ie'
 'old empires'
 'world war'
 'europe'
 'philosophical shambles'
 'mrica'
 'asia'
 'america'
 'black people'
 'manchester'
 'england'
 'pan-mrican congress'
 'mrica'
 'non-aligned'
 'bandung'
 'indonesia'
 'mao'
 u"'s revolution"
 'china'
 'mau ma'
 'kenya'
 'colonial masters'
 'algeria'
 'tunisia'
 'morocco'
 'cameroon'
 'madagascar'
 'humiliating defeat'
 'viet minh'
 'dien bien ph'
 'revolt'
 'india'
 'philippines'
 'guyana'
 'egypt'
 'guatemala'
 'mrica'
 'alabama'
 'mississippi'
 'georgia'
 'harlem'
 'revolt'
 'malcolm x'
 'extraordinary moment'
 'long decade'
 'world war'
 'late 1950s'
 'tidal wave'
 'discourse'
 'colonialism'
 'key texts'
 'tidal wave'
 'anticolonial literature'
 'postwar period-works'
 'w.e.b'
 'bois'
 'color'
 'democrary'
 'worldandafrica'
 'frantz fanon'
 'black skin'
 'masks'
 'george padmore'
 'pan-africanism'
 'coming struggle'
 'africa'
 'albert memmi'
 'colonizer'
 'colonized'
 'richard wright'
 'white man'
 'listen'
 'jean-paul'
 u"'s essay"
 'black or.pheus'
 'presence africaine'
 'aftican revolution'
 'radical literature'
 'discourse'
 'colonial question front'
 'cesaire'
 'communist affiliation'
 'modern proletariat'
 'revolutionary force'
 'hegelian'
 'cesaire'
 'immorality constitute'
 'dead weight'
 'master class'
 'colonial power'
 'brutal violence'
 'end result'
 'europe'
 'hence'
 'europe'
 'europe'
 'anticipating fanon'
 'famous propo.sition'
 'europe'
 'cesaire'
 u"world 's civilizers"
 'mricans'
 'asians'
 'colonial encounter'
 'deliberate destruction'
 'cesaire'
 'discourse'
 'cesaire'
 u"'s discourse"
 'spiritual havoc'
 'colonial discourse'
 'anticipating'
 'postcolonial studies'
 'cesaire'
 u"'s critique"
 'dominique o. mannoni'
 'roger caillois'
 'ernest renan'
 'yves florenne'
 'jules romains'
 'colonial ideology-an ideology'
 'cultural hierarchy-is'
 'colonial rule'
 'corvee labor'
 'surprisingly'
 'postcolonial criticism pay'
 'discourse'
 'robert'
 u"young 's"
 'mythologies'
 'writing history'
 'postcolonial studies'
 'fanon'
 'wretched'
 'earth'
 'fanon'
 'discourse.3'
 'literary critics'
 'discourse'
 'cesaire'
 u"'s eleven-year stint"
 'communist party'
 'martinique'
 'marxist'
 'discourse'
 'critical contributions'
 'civilization'
 'cesaire'
 'marxism'
 'marxist'
 'discourse'
 'marx'
 'w.e.b'
 'bois'
 'm.n'
 'roy'
 'anticolonial struggle supersedes'
 'proletarian revolution'
 'fundamental historical movement'
 'capitalism versus socialism'
 'colonialist system'
 'whole new world'
 'final point'
 'discourse'
 'surrealist text'
 'cesaire'
 u"'s understanding"
 'rimbaud'
 'historical materialism'
 'marxist'
 'negri'
 'tudian assertion'
 'cesaire'
 u"'s text plumbs"
 u"'s uncon.scious"
 'red book'
 'pithy quotes'
 'dancing flame'
 'aime'
 u"cesaire 's credentials"
 'colonial critic'
 'june'
 'small town'
 'bassepointe'
 'martinique'
 'local tax inspector'
 'cultural sensibilities'
 'petit bourgeois'
 'cesaires'
 'rural poverty'
 'aime'
 'precocious student'
 'lycee schoelcher'
 'fort-de-france'
 'leon.gontran damas'
 'guiana'
 'childhood soccer-mates'
 'senegalese'
 'leopold sedar senghor'
 'negritude'
 'lycee'
 'french'
 'english'
 'mother country-france'
 'antillean'
 'paris'
 'paris'
 'lycee louis-ie-grand'
 'entrance exams'
 'ecole normale superieure'
 'senghor'
 'meeting senghor'
 'senegalese'
 'ousman soce'
 'cesaire'
 'mrica'
 'negritude'
 'black diasporic'
 'intellectual circles'
 'paris'
 'nardal'
 'martinique'
 'paulette'
 'jane'
 'andree'
 'revue'
 'du monde noir'
 'paulette nardal'
 'leo sajous'
 'martinican'
 'etienne lero'
 'rene menil'
 'j.m'
 'monnerot'
 'pierre'
 'simone yoyotte'
 'communist revolution'
 'legitime'
 'french-speaking'
 'black bourgeoisie'
 'west indian literature'
 'black u.s. writers'
 'langston hughes'
 'claude mckay'
 'special attention'
 'scottsboro'
 'cesaire'
 'nardal'
 'legitime'
 'french surrealists'
 'cesaire'
 'senghor'
 'leon damas'
 'different intellectual circle'
 u"l 'etudiant noir"
 'march'
 'cesaire'
 'passionate tract'
 'negritude'
 'cesaire'
 u"'s piece"
 'european humanities'
 'entrance exams'
 'ecole normale superieure'
 'emotional costs'
 'cesaire'
 'short vacation'
 'yugoslavia'
 'fellow student'
 'adriatic'
 'cesaire'
 'small island'
 'moved'
 'long poem'
 'martinique'
 'youth-the land'
 'martinska'
 'magical chance encounter'
 'moonlit night'
 'famous poem'
 'cahier'
 u"d'un retour au"
 'notebook'
 'return'
 'native land'
 'martinique'
 'france'
 'mrican-american'
 'harlem'
 'july'
 'suzanne roussy'
 'martinican'
 u"l 'etudiant noir.7"
 'martinique'
 'fort-de-france'
 'joining'
 'rene menil'
 'lucie thesee'
 'aristide maugee'
 'georges gratiant'
 'tropiques'
 'tropiques'
 'f ranee'
 'vichy'
 'martinique'
 'guadeloupe'
 'guiana'
 'vichy'
 'cesaire'
 'french broth.erhood'
 'french'
 'literary critic'
 'a. james arnold'
 'military regime'
 'martinicans'
 'official policy'
 'cesaire'
 'anticolonialist posture'
 'official policy'
 'tropiques'
 u"group 's radicalization"
 'notorious letter'
 'may'
 'martinique'
 u"'s chief"
 'information'
 'bayle'
 'tropiques'
 'revolutionary review'
 'bayle'
 'brilliant polemical response'
 'lieutenant'
 'vaisseau bayle'
 'sir'
 'tropiques'
 'racists'
 'poisoners'
 'souls'
 'good country'
 'zola'
 'revolutionaries'
 'hugo'
 'chatiments'
 'sectarians'
 'rimbaud'
 'lau.treamont'
 'racists'
 u"toussaint l'ouverture"
 'claude mckay'
 'langston hughes'
 'drumont'
 'hitler'
 'vain recriminations'
 'signed'
 'aime cesaire'
 'suzanne cesaire'
 'georges gratiant'
 'aristide'
 'maugee'
 'rene menil'
 'lucie thesee'
 'tropiques'
 'west indian folklore'
 'tropiques'
 'radical surrealist publications'
 'lasting'
 'rene menii'
 'sophisticated anticolonial stance'
 'theirs'
 'modernism'
 'deep appreciation'
 'african modes'
 'surrealism'
 'marxism'
 'productive forces'
 'negritude'
 'marxism'
 'collective efforts'
 'profound impact'
 'international surrealism'
 'andre breton'
 'tropiques'
 'breton'
 'pierre mabille'
 'benjamin peret'
 'suzanne cesaire'
 u"surrealism 's"
 'original theorists'
 'suzanne'
 'broader movements'
 'romanticism'
 'negritude'
 'surrealism'
 'permanent readiness'
 'marvelous'
 'tropiques'
 'new possibilities'
 'marxists'
 'certain inclinations'
 'marvelous'
 'colonial domina.tion'
 'everyday life'
 'martinique'
 'surrealism'
 'us'
 u"husband 's"
 'discourse'
 'colonialism'
 'tionary attitude'
 'surrealism strengthens'
 'impatient strength'
 'massive army'
 'millions'
 'black hands'
 'furious skies'
 'world war'
 'freed'
 'sordid dichotomies'
 'europeans/afri.cans'
 'magic power'
 'colonial idiocy'
 u"welder 's"
 'blue flame'
 'unprecedented communions'
 'aime cesaire'
 'andre breton'
 'cesaire'
 'surrealism'
 'marxism'
 'non-european traditions'
 'interpretation leaves'
 'cesaires'
 'aime'
 'suzanne'
 'fresh ideas'
 'breton'
 'cesaires'
 'paris'
 'new vistas'
 'marvelous'
 'aime cesaire'
 'surrealist leanings'
 'ab'
 'surrealism'
 'surrealism'
 'powerful unconscious forces'
 'mrica'
 'french'
 'cartesian'
 'french'
 'jacqueline leiner'
 'breton'
 u"'s role"
 'breton'
 'breton'
 'breton'
 'deputy m'
 'cesaire'
 'publish poetry'
 'surrealist publications'
 'surrealism'
 'exhibit catalogue'
 'andre breton'
 'marcel duchamp'
 'surrealist imagery'
 'poetry collections'
 'les armes'
 'miraculous weapons'
 'solei'
 'cou coupe'
 'beheaded sun'
 'cesaire'
 u"'s essay"
 'poetry'
 'cognition'
 'haiti'
 'tropiques'
 'systematic statements'
 'revolutionary nature'
 'opening'
 'provocative proposition'
 'poetic'
 'great silence'
 'scientific knowledge'
 u"world 's crises"
 'cesaire'
 u"'s embrace"
 'discourse'
 'discourse'
 'historical prose poem'
 'cesaire'
 'lucid intelligence'
 'sharpest sensibility'
 'subtlest feelings'
 'life form'
 'creative im.pulse-is'
 'powerful source'
 'discourse'
 u"'s sharpest weapon"
 'war drums'
 'powerful sections'
 'systematic critique replete'
 'sufficient evidence'
 'topic sentences'
 'bullet points'
 'con.sider cesaire'
 'poetic knowledge'
 'poetic'
 'man spatters'
 'surrealism'
 'discourse'
 'pan-mricanism'
 'negritude'
 'own independent anticolonial roots'
 'cesaire'
 u"'s critique"
 'mutual attraction'
 'cesaire'
 'black intellectuals'
 'up'
 'euro.pean'
 'cultural iconoclasts'
 'radical pronouncements'
 'social revolution'
 'paris surrealist'
 'french communist party'
 'abd-el-krim'
 'rif'
 'french'
 'morocco'
 'french'
 'colonial rule'
 'letter'
 'paul claudel'
 'japan'
 'paris'
 'colonial insurrections'
 'western civilization'
 'orient'
 'paris'
 'militant statement'
 'colonial question'
 'titled'
 'murderous humanitarianism'
 'rene crevel'
 'andre breton'
 'paul eluard'
 'benjamin peret'
 'yves tanguy'
 'martinican'
 'pierre yoyotte'
 'monnerot'
 'relentless attack'
 'black bourgeoisie'
 'hypocritical liberals'
 'surrealists'
 'imperialist war'
 'colonial form'
 'civil war'
 'colonial problem'
 'color question'
 'murderous humanitarianism'
 'cesaire'
 u"'s critique"
 'european proletariat'
 'more.over'
 'world war'
 'discourse'
 'direct link'
 'cesaire'
 'europeans'
 'nazism'
 'non-european peoples'
 'nazism'
 'whole edifice'
 'christian civilization'
 'real crime'
 'white people'
 'colonial procedures'
 'arabs'
 'algeria'
 'mrica'
 'situate cesaire'
 'radical black intellectuals'
 'discourse'
 'cedric robinson'
 'radical black intellectuals'
 'w.e.b'
 'bois'
 'c.l.r james'
 'george padmore'
 'oliver cox'
 'logical development'
 'civilization'
 'global systems'
 'political economy'
 'racist ideologies'
 'ralph bunche'
 'radical political science professor'
 'howard'
 'imperialism birth'
 'fascisin'
 'bunche'
 'extreme jingoism'
 'comic-opera glorification'
 'world imperialism'
 'ruthless exploitation'
 'darker populations'
 'bois'
 'clearest statements'
 'hitler'
 'mussolini'
 'race prejudice'
 'white people'
 'britain'
 'france'
 'nazis'
 'africa'
 'nazi'
 'atrocity-concentration camps'
 'mur- der'
 'ghastly blasphemy'
 'christian civilization'
 'europe'
 'superior race'
 'superior race'
 'discourse'
 'negrirude'
 u"'s impulse"
 'mrica'
 u"'s accomplish.ments"
 'takirig'
 'leo frobenius'
 u"'s injunction"
 'negro'
 'european invention'
 'cesaire'
 'colonial mission'
 'smoke screen'
 'colonialism results'
 'massive destruction'
 'whole societies-societies'
 'high level'
 'valuable lessons'
 'modern world'
 u"cesaire 's insistence"
 'mrican'
 'asian cultures'
 'ante-capitalist ...'
 'romantic claims'
 'african nationalist leaders'
 'julius nyerere'
 'kenneth kaunda'
 'senghor'
 'africa'
 'pre-colonial village life'
 'discourse'
 'cesaire'
 'intro.duction'
 'victor schoelcher'
 'esclavage'
 'erect cities'
 'cultivate fields'
 'weave cotton'
 'forge steel'
 'own beauty'
 'mystical connections'
 'mutual assistance'
 'free accep'
 'order-earnestness-poetry'
 'free'
 'reading'
 'cesaire'
 u"'s brightest students"
 'frantz fanon'
 'africa'
 'black skin'
 'masks'
 'valid historical place'
 'white man'
 'negritude'
 'miraculous weapon'
 'negro'
 'cedric robinson'
 'black marxism'
 'making'
 'black radical tradition'
 'easy task'
 'negro'
 'racial boundary'
 'immense expenditures'
 'intellectual energies'
 'entire generation'
 'european scholars'
 'intellecrual contributions'
 'egypt'
 'nubia'
 'european history'
 'africa'
 'whole continent'
 'brutish heathens'
 'europe'
 'pure entity'
 'negro'
 'cesaire'
 u"'s construction"
 'africa'
 'communal societies'
 'old friend'
 'senghor'
 'cesaire'
 u"'s concept"
 'negritude'
 'discourse'
 'sterile attempt'
 'dead society'
 'exoticism .. ..'
 'new society'
 'brother slaves'
 'productive power'
 'modern times'
 'olden days'
 'soviet union'
 'cesaire'
 'communist party'
 'martinique'
 'communist ticket'
 'fort-de-france'
 'french national assembly'
 'stalinism'
 'circa 1950s'
 'new society'
 'great poet'
 'major voice'
 'negritude'
 'communist party'
 'postwar world'
 'communist parties worldwide'
 'europe'
 'joe stalin'
 'war years'
 'liberal democracy'
 'caribbean'
 'america'
 'cesaire'
 u"'s friends"
 'jacques romain'
 'nicolas guillen'
 'rene depestre'
 'cesaire'
 'cesaire'
 'martinique'
 'guadeloupe'
 'guiana'
 'reunion'
 'french republic'
 'departmentaliza.tion'
 'france'
 u"cesaire 's eloquent"
 'pas.sionate arguments'
 'old colonies'
 'equal rights'
 'pipe dream'
 'french officials'
 'martini.can'
 'discourse'
 'outspoken critic'
 'departmenta lzatlon ..'
 'i\ufffd'
 u"cesaire 's role"
 'communist leader'
 u"discourse'snod"
 'soviet union'
 'names proletarian revolution'
 'europe'
 'colonial violence'
 'silent complicity'
 'proletarian revolution'
 'final solution'
 'fanon'
 'europe'
 'european bourgeoisie'
 'discourse'
 'marxism'
 'anti-rationalist ideas'
 'cesaire'
 'early poetry'
 'negritude'
 'new spiritual values'
 'cesaire'
 u"'s position vis-a.-vis"
 'marxism'
 'discourse'
 'october'
 'cesaire'
 'famous letter'
 'maurice thorez'
 'french communist party'
 'stalinism'
 'colonial question-not'
 u"party 's policies"
 'colonial relationship berween'
 'martinican'
 'parties'
 'arguing'
 'color need'
 'colonial question ...'
 'subsidiary part'
 'important global matter'
 'racism'
 'class struggle'
 'direct assertion'
 'world unity'
 'dis.course'
 'marxist'
 'communist party'
 'west indian islands'
 'africa'
 u"'s child"
 'chill abstractions'
 'cesaire'
 u"'s investment"
 'third-world revolt'
 'new society'
 'fanon'
 'europe'
 'old humanism'
 'europe'
 'cesaire'
 u"''i 'm"
 'narrow particularism'
 'universalism ...'
 'different idea'
 'cesaire'
 'discourse'
 'thorez'
 'african intellectual circles'
 'pervasive spirit'
 'negritude'
 'simple matter'
 'racial essentialism'
 'critic'
 'manthia diawara'
 'radical critiques'
 'colonial order'
 'discourse'
 'colonialism'
 'new generation'
 'negritude'
 'africa'
 'international moment'
 'universal emanci.pation'
 'universal freedom'
 'people worldwide-all'
 'important identity'
 'new historical mission'
 'archaic identities'
 'religious entrap.ments'
 'french'
 'recent events-genocide'
 'africa'
 'cuba'
 'progressive movements'
 'cesaire'
 'fanon'
 u"'s predictions"
 'colonial language'
 'cesaire critiques'
 'formal sense'
 'colonial state'
 'old colonial state'
 'primary difference'
 'black faces'
 'new ruling class-the class'
 'fanon'
 'colonial masters'
 'new jack u.s.'
 'corporate rulers'
 'stalinists'
 'colonial discourse'
 'cesaire'
 'true radicals'
 'postcolonial theoty'
 'official apparatus'
 'cultural links'
 'colonial domination'
 'discourse'
 'political economy'
 'colonial domination'
 'whole way'
 'european terms'
 'discourse'
 u"master class 's ideology"
 'fanon'
 'cesaire'
 'europe'
 u"'s footsteps"
 'ancient way'
 'new direction altogether'
 'cesaire'
 'martinique'
 'fort-de.france'
 'brief pages'
 'old political parties'
 'labor exploitation'
 'different way'
 'discourse'
 'road map'
 'cesaire'
 'own miraculous weapons'
 'tropiques'
 'vichy'
 'european culture'
 'france'
 'native land'
 'revolutionary graffiti'
 'bold strokes'
 'great texts'
 'civilization'
 'hand grenade'
 'new history'
 'discourse'
 'dead docu.ment'
 'dead order'
 'different way'
 'cesaire'
 'lautn'
 u"amont 's"
 'chants'
 'maldoror'
 'can.nibalistic nature'
 'poetic knowledge'
 'discourse'
 'new insights'
 'postcolonial predicament'
 'old colonial order'
 'malcolm x'
 'ballot'
 'bullet'
 'speech'
 'april'
 'malcolm x'
 'prominent members'
 'civil rights movement'
 'cory'
 'methodist church'
 'cleveland'
 'ohio'
 'april'
 'black populace'
 'important time'
 'malcolm x'
 u"'s life"
 'nation'
 'islam'
 'negro revolt'
 'humble way'
 'democrat'
 'republican'
 'hunkies'
 'polacks'
 'italian refugees'
 'europe'
 'well'
 'america'
 u"n't need"
 u"n't need"
 'washington'
 'd.c.'
 'civil-rights legislation'
 'polack'
 'black people'
 'americanism'
 'black people'
 'i.'
 'american dream system'
 'america'
 'american dream'
 'american nightmare'
 'new friends'
 'new allies'
 'civil-rights struggle'
 'human rights'
 'whenever'
 'civil-rights struggle'
 'uncle sam'
 'outside world'
 'civil-rights struggle'
 'civil rights'
 'domestic affairs'
 'african brothers'
 'asian brothers'
 'latin-american'
 'domestic affairs'
 'civil rights'
 'uncle sam'
 'human rights'
 'human rights'
 'africa'
 'hungary'
 'asia'
 'america'
 'negro'
 'human rights'
 'civil rights'
 'civil-rights tree'
 'human-rights tree'
 'civil-rights struggle'
 'human rights'
 'black man'
 'general assembly'
 'uncle sam'
 'world court'
 'human rights'
 'civil rights'
 'civil rights'
 'civil rights means'
 'uncle sam'
 'human rights'
 'human rights'
 'world court'
 'uncle sam'
 u"'s hands"
 'black man'
 u"earth 's number-one hypocrite"
 'free world'
 'free world'
 'shall overcome'
 'expand'
 'civil-rights struggle'
 'human rights'
 'african brothers'
 'latin-american'
 'chinamen'
 'washington'
 'd.c.'
 'political chicanery'
 'america'
 'tin soldier'
 'uncle sam'
 'know\ufffd\ufffd\ufffdi disagree'
 'lomax'
 'poor nations'
 'poor nations'
 'rich nations'
 'nation\ufffd\ufffd\ufffdone vote'
 'equal vote'
 'asia'
 'africa'
 'darker parts'
 'sam'
 'russia'
 'right'
 'african-americans\ufffd\ufffd\ufffdthat'
 'america'
 'africans'
 'africans'
 'negro'
 'africans'
 u"n't catch hell"
 'civil-rights bills'
 'africans'
 'negro'
 'hoogagagooba'
 u"'ll show"
 'white man'
 'silly man'
 'atlanta'
 'white restaurant'
 'negro'
 'nigger dare'
 'muslim mosque'
 'york'
 'muslims'
 'islam'
 u"n't mix"
 'civil activities\ufffd\ufffd\ufffdnot'
 'religious services'
 'muslims'
 'political action'
 'economic action'
 'civic action'
 'social evils'
 'political philosophy'
 'black nationalism'
 'black man'
 'own community'
 'black man'
 'black community'
 'political philosophy'
 'black nationalism'
 'christian church'
 'naacp'
 'core'
 'sncc'
 '[ student'
 'nonviolent coordinating'
 'committee ] meetings'
 'muslim'
 'black'
 'shall overcome'
 'economic philosophy'
 'black nationalism'
 'white people'
 'white people'
 'white man'
 u"black man ca n't"
 'white community'
 'white man'
 'black community'
 'black nationalism involves'
 're-education program'
 'black community'
 'slum area'
 'white man'
 'economic philosophy'
 'black nationalism'
 'civic organization'
 'fraternal order'
 u"'s time"
 'own community'
 'own kind'
 'gain control'
 'own community'
 'social philosophy'
 'black nationalism'
 'drug addiction'
 'moral fiber'
 'own society'
 'own social circles'
 u"wo n't"
 'social circle'
 'great controversy'
 u"'s time"
 'article'
 'constitutional amendments'
 'white folks'
 'white man'
 'black man buying rifles'
 'white man'
 'malcolm'
 'uncle tom'
 'amen'
 'tom'
 'rifle clubs'
 'defense budget'
 u"ca n't begrudge"
 'medals'
 'big\ufffd\ufffd\ufffdany time'
 'cold blood'
 'white man'
 u"ca n't"
 'eichmann'
 'argentina'
 'american soldiers'
 u"'s business way"
 'vietnam'
 'cuba'
 'free elections\ufffd\ufffd\ufffdthis'
 'old cracker'
 'free elections'
 'own country'
 'negro'
 'cracker senator'
 'black people'
 'washington'
 'shall overcome'
 'white friends'
 'round-trip tickets'
 'one-way tickets'
 'non-violent army'
 'black nationalists'
 'lyndon b. johnson'
 'democratic party'
 'civil rights'
 'moral stand\ufffd\ufffd\ufffdright'
 'election time'
 'thank']
['discourse on colonialism aime cesaire translated'
 'joan pinkham'
 'poetics of anticolonialism'
 'robin d. g. kelley'
 'introduction'
 'poetics of anticolonialism robin d. g. kelley aime cesaire'
 'discourse'
 'colonialism'
 'world manifesto'
 'old order bereft'
 'accompany manifestos'
 'discourse'
 'revolutionary ca.dences'
 'marx'
 'engels'
 'discours'
 'ie'
 'old empires'
 'world war'
 'europe'
 'philosophical shambles'
 'mrica'
 'asia'
 'america'
 'black people'
 'manchester'
 'england'
 'pan-mrican congress'
 'mrica'
 'non-aligned'
 'bandung'
 'indonesia'
 'mao'
 u"'s revolution"
 'china'
 'mau ma'
 'kenya'
 'colonial masters'
 'algeria'
 'tunisia'
 'morocco'
 'cameroon'
 'madagascar'
 'humiliating defeat'
 'viet minh'
 'dien bien ph'
 'revolt'
 'india'
 'philippines'
 'guyana'
 'egypt'
 'guatemala'
 'mrica'
 'alabama'
 'mississippi'
 'georgia'
 'harlem'
 'revolt'
 'malcolm x'
 'extraordinary moment'
 'long decade'
 'world war'
 'late 1950s'
 'tidal wave'
 'discourse'
 'colonialism'
 'key texts'
 'tidal wave'
 'anticolonial literature'
 'postwar period-works'
 'w.e.b'
 'bois'
 'color'
 'democrary'
 'worldandafrica'
 'frantz fanon'
 'black skin'
 'masks'
 'george padmore'
 'pan-africanism'
 'coming struggle'
 'africa'
 'albert memmi'
 'colonizer'
 'colonized'
 'richard wright'
 'white man'
 'listen'
 'jean-paul'
 u"'s essay"
 'black or.pheus'
 'presence africaine'
 'aftican revolution'
 'radical literature'
 'discourse'
 'colonial question front'
 'cesaire'
 'communist affiliation'
 'modern proletariat'
 'revolutionary force'
 'hegelian'
 'cesaire'
 'immorality constitute'
 'dead weight'
 'master class'
 'colonial power'
 'brutal violence'
 'end result'
 'europe'
 'hence'
 'europe'
 'europe'
 'anticipating fanon'
 'famous propo.sition'
 'europe'
 'cesaire'
 u"world 's civilizers"
 'mricans'
 'asians'
 'colonial encounter'
 'deliberate destruction'
 'cesaire'
 'discourse'
 'cesaire'
 u"'s discourse"
 'spiritual havoc'
 'colonial discourse'
 'anticipating'
 'postcolonial studies'
 'cesaire'
 u"'s critique"
 'dominique o. mannoni'
 'roger caillois'
 'ernest renan'
 'yves florenne'
 'jules romains'
 'colonial ideology-an ideology'
 'cultural hierarchy-is'
 'colonial rule'
 'corvee labor'
 'surprisingly'
 'postcolonial criticism pay'
 'discourse'
 'robert'
 u"young 's"
 'mythologies'
 'writing history'
 'postcolonial studies'
 'fanon'
 'wretched'
 'earth'
 'fanon'
 'discourse.3'
 'literary critics'
 'discourse'
 'cesaire'
 u"'s eleven-year stint"
 'communist party'
 'martinique'
 'marxist'
 'discourse'
 'critical contributions'
 'civilization'
 'cesaire'
 'marxism'
 'marxist'
 'discourse'
 'marx'
 'w.e.b'
 'bois'
 'm.n'
 'roy'
 'anticolonial struggle supersedes'
 'proletarian revolution'
 'fundamental historical movement'
 'capitalism versus socialism'
 'colonialist system'
 'whole new world'
 'final point'
 'discourse'
 'surrealist text'
 'cesaire'
 u"'s understanding"
 'rimbaud'
 'historical materialism'
 'marxist'
 'negri'
 'tudian assertion'
 'cesaire'
 u"'s text plumbs"
 u"'s uncon.scious"
 'red book'
 'pithy quotes'
 'dancing flame'
 'aime'
 u"cesaire 's credentials"
 'colonial critic'
 'june'
 'small town'
 'bassepointe'
 'martinique'
 'local tax inspector'
 'cultural sensibilities'
 'petit bourgeois'
 'cesaires'
 'rural poverty'
 'aime'
 'precocious student'
 'lycee schoelcher'
 'fort-de-france'
 'leon.gontran damas'
 'guiana'
 'childhood soccer-mates'
 'senegalese'
 'leopold sedar senghor'
 'negritude'
 'lycee'
 'french'
 'english'
 'mother country-france'
 'antillean'
 'paris'
 'paris'
 'lycee louis-ie-grand'
 'entrance exams'
 'ecole normale superieure'
 'senghor'
 'meeting senghor'
 'senegalese'
 'ousman soce'
 'cesaire'
 'mrica'
 'negritude'
 'black diasporic'
 'intellectual circles'
 'paris'
 'nardal'
 'martinique'
 'paulette'
 'jane'
 'andree'
 'revue'
 'du monde noir'
 'paulette nardal'
 'leo sajous'
 'martinican'
 'etienne lero'
 'rene menil'
 'j.m'
 'monnerot'
 'pierre'
 'simone yoyotte'
 'communist revolution'
 'legitime'
 'french-speaking'
 'black bourgeoisie'
 'west indian literature'
 'black u.s. writers'
 'langston hughes'
 'claude mckay'
 'special attention'
 'scottsboro'
 'cesaire'
 'nardal'
 'legitime'
 'french surrealists'
 'cesaire'
 'senghor'
 'leon damas'
 'different intellectual circle'
 u"l 'etudiant noir"
 'march'
 'cesaire'
 'passionate tract'
 'negritude'
 'cesaire'
 u"'s piece"
 'european humanities'
 'entrance exams'
 'ecole normale superieure'
 'emotional costs'
 'cesaire'
 'short vacation'
 'yugoslavia'
 'fellow student'
 'adriatic'
 'cesaire'
 'small island'
 'moved'
 'long poem'
 'martinique'
 'youth-the land'
 'martinska'
 'magical chance encounter'
 'moonlit night'
 'famous poem'
 'cahier'
 u"d'un retour au"
 'notebook'
 'return'
 'native land'
 'martinique'
 'france'
 'mrican-american'
 'harlem'
 'july'
 'suzanne roussy'
 'martinican'
 u"l 'etudiant noir.7"
 'martinique'
 'fort-de-france'
 'joining'
 'rene menil'
 'lucie thesee'
 'aristide maugee'
 'georges gratiant'
 'tropiques'
 'tropiques'
 'f ranee'
 'vichy'
 'martinique'
 'guadeloupe'
 'guiana'
 'vichy'
 'cesaire'
 'french broth.erhood'
 'french'
 'literary critic'
 'a. james arnold'
 'military regime'
 'martinicans'
 'official policy'
 'cesaire'
 'anticolonialist posture'
 'official policy'
 'tropiques'
 u"group 's radicalization"
 'notorious letter'
 'may'
 'martinique'
 u"'s chief"
 'information'
 'bayle'
 'tropiques'
 'revolutionary review'
 'bayle'
 'brilliant polemical response'
 'lieutenant'
 'vaisseau bayle'
 'sir'
 'tropiques'
 'racists'
 'poisoners'
 'souls'
 'good country'
 'zola'
 'revolutionaries'
 'hugo'
 'chatiments'
 'sectarians'
 'rimbaud'
 'lau.treamont'
 'racists'
 u"toussaint l'ouverture"
 'claude mckay'
 'langston hughes'
 'drumont'
 'hitler'
 'vain recriminations'
 'signed'
 'aime cesaire'
 'suzanne cesaire'
 'georges gratiant'
 'aristide'
 'maugee'
 'rene menil'
 'lucie thesee'
 'tropiques'
 'west indian folklore'
 'tropiques'
 'radical surrealist publications'
 'lasting'
 'rene menii'
 'sophisticated anticolonial stance'
 'theirs'
 'modernism'
 'deep appreciation'
 'african modes'
 'surrealism'
 'marxism'
 'productive forces'
 'negritude'
 'marxism'
 'collective efforts'
 'profound impact'
 'international surrealism'
 'andre breton'
 'tropiques'
 'breton'
 'pierre mabille'
 'benjamin peret'
 'suzanne cesaire'
 u"surrealism 's"
 'original theorists'
 'suzanne'
 'broader movements'
 'romanticism'
 'negritude'
 'surrealism'
 'permanent readiness'
 'marvelous'
 'tropiques'
 'new possibilities'
 'marxists'
 'certain inclinations'
 'marvelous'
 'colonial domina.tion'
 'everyday life'
 'martinique'
 'surrealism'
 'us'
 u"husband 's"
 'discourse'
 'colonialism'
 'tionary attitude'
 'surrealism strengthens'
 'impatient strength'
 'massive army'
 'millions'
 'black hands'
 'furious skies'
 'world war'
 'freed'
 'sordid dichotomies'
 'europeans/afri.cans'
 'magic power'
 'colonial idiocy'
 u"welder 's"
 'blue flame'
 'unprecedented communions'
 'aime cesaire'
 'andre breton'
 'cesaire'
 'surrealism'
 'marxism'
 'non-european traditions'
 'interpretation leaves'
 'cesaires'
 'aime'
 'suzanne'
 'fresh ideas'
 'breton'
 'cesaires'
 'paris'
 'new vistas'
 'marvelous'
 'aime cesaire'
 'surrealist leanings'
 'ab'
 'surrealism'
 'surrealism'
 'powerful unconscious forces'
 'mrica'
 'french'
 'cartesian'
 'french'
 'jacqueline leiner'
 'breton'
 u"'s role"
 'breton'
 'breton'
 'breton'
 'deputy m'
 'cesaire'
 'publish poetry'
 'surrealist publications'
 'surrealism'
 'exhibit catalogue'
 'andre breton'
 'marcel duchamp'
 'surrealist imagery'
 'poetry collections'
 'les armes'
 'miraculous weapons'
 'solei'
 'cou coupe'
 'beheaded sun'
 'cesaire'
 u"'s essay"
 'poetry'
 'cognition'
 'haiti'
 'tropiques'
 'systematic statements'
 'revolutionary nature'
 'opening'
 'provocative proposition'
 'poetic'
 'great silence'
 'scientific knowledge'
 u"world 's crises"
 'cesaire'
 u"'s embrace"
 'discourse'
 'discourse'
 'historical prose poem'
 'cesaire'
 'lucid intelligence'
 'sharpest sensibility'
 'subtlest feelings'
 'life form'
 'creative im.pulse-is'
 'powerful source'
 'discourse'
 u"'s sharpest weapon"
 'war drums'
 'powerful sections'
 'systematic critique replete'
 'sufficient evidence'
 'topic sentences'
 'bullet points'
 'con.sider cesaire'
 'poetic knowledge'
 'poetic'
 'man spatters'
 'surrealism'
 'discourse'
 'pan-mricanism'
 'negritude'
 'own independent anticolonial roots'
 'cesaire'
 u"'s critique"
 'mutual attraction'
 'cesaire'
 'black intellectuals'
 'up'
 'euro.pean'
 'cultural iconoclasts'
 'radical pronouncements'
 'social revolution'
 'paris surrealist'
 'french communist party'
 'abd-el-krim'
 'rif'
 'french'
 'morocco'
 'french'
 'colonial rule'
 'letter'
 'paul claudel'
 'japan'
 'paris'
 'colonial insurrections'
 'western civilization'
 'orient'
 'paris'
 'militant statement'
 'colonial question'
 'titled'
 'murderous humanitarianism'
 'rene crevel'
 'andre breton'
 'paul eluard'
 'benjamin peret'
 'yves tanguy'
 'martinican'
 'pierre yoyotte'
 'monnerot'
 'relentless attack'
 'black bourgeoisie'
 'hypocritical liberals'
 'surrealists'
 'imperialist war'
 'colonial form'
 'civil war'
 'colonial problem'
 'color question'
 'murderous humanitarianism'
 'cesaire'
 u"'s critique"
 'european proletariat'
 'more.over'
 'world war'
 'discourse'
 'direct link'
 'cesaire'
 'europeans'
 'nazism'
 'non-european peoples'
 'nazism'
 'whole edifice'
 'christian civilization'
 'real crime'
 'white people'
 'colonial procedures'
 'arabs'
 'algeria'
 'mrica'
 'situate cesaire'
 'radical black intellectuals'
 'discourse'
 'cedric robinson'
 'radical black intellectuals'
 'w.e.b'
 'bois'
 'c.l.r james'
 'george padmore'
 'oliver cox'
 'logical development'
 'civilization'
 'global systems'
 'political economy'
 'racist ideologies'
 'ralph bunche'
 'radical political science professor'
 'howard'
 'imperialism birth'
 'fascisin'
 'bunche'
 'extreme jingoism'
 'comic-opera glorification'
 'world imperialism'
 'ruthless exploitation'
 'darker populations'
 'bois'
 'clearest statements'
 'hitler'
 'mussolini'
 'race prejudice'
 'white people'
 'britain'
 'france'
 'nazis'
 'africa'
 'nazi'
 'atrocity-concentration camps'
 'mur- der'
 'ghastly blasphemy'
 'christian civilization'
 'europe'
 'superior race'
 'superior race'
 'discourse'
 'negrirude'
 u"'s impulse"
 'mrica'
 u"'s accomplish.ments"
 'takirig'
 'leo frobenius'
 u"'s injunction"
 'negro'
 'european invention'
 'cesaire'
 'colonial mission'
 'smoke screen'
 'colonialism results'
 'massive destruction'
 'whole societies-societies'
 'high level'
 'valuable lessons'
 'modern world'
 u"cesaire 's insistence"
 'mrican'
 'asian cultures'
 'ante-capitalist ...'
 'romantic claims'
 'african nationalist leaders'
 'julius nyerere'
 'kenneth kaunda'
 'senghor'
 'africa'
 'pre-colonial village life'
 'discourse'
 'cesaire'
 'intro.duction'
 'victor schoelcher'
 'esclavage'
 'erect cities'
 'cultivate fields'
 'weave cotton'
 'forge steel'
 'own beauty'
 'mystical connections'
 'mutual assistance'
 'free accep'
 'order-earnestness-poetry'
 'free'
 'reading'
 'cesaire'
 u"'s brightest students"
 'frantz fanon'
 'africa'
 'black skin'
 'masks'
 'valid historical place'
 'white man'
 'negritude'
 'miraculous weapon'
 'negro'
 'cedric robinson'
 'black marxism'
 'making'
 'black radical tradition'
 'easy task'
 'negro'
 'racial boundary'
 'immense expenditures'
 'intellectual energies'
 'entire generation'
 'european scholars'
 'intellecrual contributions'
 'egypt'
 'nubia'
 'european history'
 'africa'
 'whole continent'
 'brutish heathens'
 'europe'
 'pure entity'
 'negro'
 'cesaire'
 u"'s construction"
 'africa'
 'communal societies'
 'old friend'
 'senghor'
 'cesaire'
 u"'s concept"
 'negritude'
 'discourse'
 'sterile attempt'
 'dead society'
 'exoticism .. ..'
 'new society'
 'brother slaves'
 'productive power'
 'modern times'
 'olden days'
 'soviet union'
 'cesaire'
 'communist party'
 'martinique'
 'communist ticket'
 'fort-de-france'
 'french national assembly'
 'stalinism'
 'circa 1950s'
 'new society'
 'great poet'
 'major voice'
 'negritude'
 'communist party'
 'postwar world'
 'communist parties worldwide'
 'europe'
 'joe stalin'
 'war years'
 'liberal democracy'
 'caribbean'
 'america'
 'cesaire'
 u"'s friends"
 'jacques romain'
 'nicolas guillen'
 'rene depestre'
 'cesaire'
 'cesaire'
 'martinique'
 'guadeloupe'
 'guiana'
 'reunion'
 'french republic'
 'departmentaliza.tion'
 'france'
 u"cesaire 's eloquent"
 'pas.sionate arguments'
 'old colonies'
 'equal rights'
 'pipe dream'
 'french officials'
 'martini.can'
 'discourse'
 'outspoken critic'
 'departmenta lzatlon ..'
 'i\ufffd'
 u"cesaire 's role"
 'communist leader'
 u"discourse'snod"
 'soviet union'
 'names proletarian revolution'
 'europe'
 'colonial violence'
 'silent complicity'
 'proletarian revolution'
 'final solution'
 'fanon'
 'europe'
 'european bourgeoisie'
 'discourse'
 'marxism'
 'anti-rationalist ideas'
 'cesaire'
 'early poetry'
 'negritude'
 'new spiritual values'
 'cesaire'
 u"'s position vis-a.-vis"
 'marxism'
 'discourse'
 'october'
 'cesaire'
 'famous letter'
 'maurice thorez'
 'french communist party'
 'stalinism'
 'colonial question-not'
 u"party 's policies"
 'colonial relationship berween'
 'martinican'
 'parties'
 'arguing'
 'color need'
 'colonial question ...'
 'subsidiary part'
 'important global matter'
 'racism'
 'class struggle'
 'direct assertion'
 'world unity'
 'dis.course'
 'marxist'
 'communist party'
 'west indian islands'
 'africa'
 u"'s child"
 'chill abstractions'
 'cesaire'
 u"'s investment"
 'third-world revolt'
 'new society'
 'fanon'
 'europe'
 'old humanism'
 'europe'
 'cesaire'
 u"''i 'm"
 'narrow particularism'
 'universalism ...'
 'different idea'
 'cesaire'
 'discourse'
 'thorez'
 'african intellectual circles'
 'pervasive spirit'
 'negritude'
 'simple matter'
 'racial essentialism'
 'critic'
 'manthia diawara'
 'radical critiques'
 'colonial order'
 'discourse'
 'colonialism'
 'new generation'
 'negritude'
 'africa'
 'international moment'
 'universal emanci.pation'
 'universal freedom'
 'people worldwide-all'
 'important identity'
 'new historical mission'
 'archaic identities'
 'religious entrap.ments'
 'french'
 'recent events-genocide'
 'africa'
 'cuba'
 'progressive movements'
 'cesaire'
 'fanon'
 u"'s predictions"
 'colonial language'
 'cesaire critiques'
 'formal sense'
 'colonial state'
 'old colonial state'
 'primary difference'
 'black faces'
 'new ruling class-the class'
 'fanon'
 'colonial masters'
 'new jack u.s.'
 'corporate rulers'
 'stalinists'
 'colonial discourse'
 'cesaire'
 'true radicals'
 'postcolonial theoty'
 'official apparatus'
 'cultural links'
 'colonial domination'
 'discourse'
 'political economy'
 'colonial domination'
 'whole way'
 'european terms'
 'discourse'
 u"master class 's ideology"
 'fanon'
 'cesaire'
 'europe'
 u"'s footsteps"
 'ancient way'
 'new direction altogether'
 'cesaire'
 'martinique'
 'fort-de.france'
 'brief pages'
 'old political parties'
 'labor exploitation'
 'different way'
 'discourse'
 'road map'
 'cesaire'
 'own miraculous weapons'
 'tropiques'
 'vichy'
 'european culture'
 'france'
 'native land'
 'revolutionary graffiti'
 'bold strokes'
 'great texts'
 'civilization'
 'hand grenade'
 'new history'
 'discourse'
 'dead docu.ment'
 'dead order'
 'different way'
 'cesaire'
 'lautn'
 u"amont 's"
 'chants'
 'maldoror'
 'can.nibalistic nature'
 'poetic knowledge'
 'discourse'
 'new insights'
 'postcolonial predicament'
 'old colonial order'
 'malcolm x'
 'ballot'
 'bullet'
 'speech'
 'april'
 'malcolm x'
 'prominent members'
 'civil rights movement'
 'cory'
 'methodist church'
 'cleveland'
 'ohio'
 'april'
 'black populace'
 'important time'
 'malcolm x'
 u"'s life"
 'nation'
 'islam'
 'negro revolt'
 'humble way'
 'democrat'
 'republican'
 'hunkies'
 'polacks'
 'italian refugees'
 'europe'
 'well'
 'america'
 u"n't need"
 u"n't need"
 'washington'
 'd.c.'
 'civil-rights legislation'
 'polack'
 'black people'
 'americanism'
 'black people'
 'i.'
 'american dream system'
 'america'
 'american dream'
 'american nightmare'
 'new friends'
 'new allies'
 'civil-rights struggle'
 'human rights'
 'whenever'
 'civil-rights struggle'
 'uncle sam'
 'outside world'
 'civil-rights struggle'
 'civil rights'
 'domestic affairs'
 'african brothers'
 'asian brothers'
 'latin-american'
 'domestic affairs'
 'civil rights'
 'uncle sam'
 'human rights'
 'human rights'
 'africa'
 'hungary'
 'asia'
 'america'
 'negro'
 'human rights'
 'civil rights'
 'civil-rights tree'
 'human-rights tree'
 'civil-rights struggle'
 'human rights'
 'black man'
 'general assembly'
 'uncle sam'
 'world court'
 'human rights'
 'civil rights'
 'civil rights'
 'civil rights means'
 'uncle sam'
 'human rights'
 'human rights'
 'world court'
 'uncle sam'
 u"'s hands"
 'black man'
 u"earth 's number-one hypocrite"
 'free world'
 'free world'
 'shall overcome'
 'expand'
 'civil-rights struggle'
 'human rights'
 'african brothers'
 'latin-american'
 'chinamen'
 'washington'
 'd.c.'
 'political chicanery'
 'america'
 'tin soldier'
 'uncle sam'
 'know\ufffd\ufffd\ufffdi disagree'
 'lomax'
 'poor nations'
 'poor nations'
 'rich nations'
 'nation\ufffd\ufffd\ufffdone vote'
 'equal vote'
 'asia'
 'africa'
 'darker parts'
 'sam'
 'russia'
 'right'
 'african-americans\ufffd\ufffd\ufffdthat'
 'america'
 'africans'
 'africans'
 'negro'
 'africans'
 u"n't catch hell"
 'civil-rights bills'
 'africans'
 'negro'
 'hoogagagooba'
 u"'ll show"
 'white man'
 'silly man'
 'atlanta'
 'white restaurant'
 'negro'
 'nigger dare'
 'muslim mosque'
 'york'
 'muslims'
 'islam'
 u"n't mix"
 'civil activities\ufffd\ufffd\ufffdnot'
 'religious services'
 'muslims'
 'political action'
 'economic action'
 'civic action'
 'social evils'
 'political philosophy'
 'black nationalism'
 'black man'
 'own community'
 'black man'
 'black community'
 'political philosophy'
 'black nationalism'
 'christian church'
 'naacp'
 'core'
 'sncc'
 '[ student'
 'nonviolent coordinating'
 'committee ] meetings'
 'muslim'
 'black'
 'shall overcome'
 'economic philosophy'
 'black nationalism'
 'white people'
 'white people'
 'white man'
 u"black man ca n't"
 'white community'
 'white man'
 'black community'
 'black nationalism involves'
 're-education program'
 'black community'
 'slum area'
 'white man'
 'economic philosophy'
 'black nationalism'
 'civic organization'
 'fraternal order'
 u"'s time"
 'own community'
 'own kind'
 'gain control'
 'own community'
 'social philosophy'
 'black nationalism'
 'drug addiction'
 'moral fiber'
 'own society'
 'own social circles'
 u"wo n't"
 'social circle'
 'great controversy'
 u"'s time"
 'article'
 'constitutional amendments'
 'white folks'
 'white man'
 'black man buying rifles'
 'white man'
 'malcolm'
 'uncle tom'
 'amen'
 'tom'
 'rifle clubs'
 'defense budget'
 u"ca n't begrudge"
 'medals'
 'big\ufffd\ufffd\ufffdany time'
 'cold blood'
 'white man'
 u"ca n't"
 'eichmann'
 'argentina'
 'american soldiers'
 u"'s business way"
 'vietnam'
 'cuba'
 'free elections\ufffd\ufffd\ufffdthis'
 'old cracker'
 'free elections'
 'own country'
 'negro'
 'cracker senator'
 'black people'
 'washington'
 'shall overcome'
 'white friends'
 'round-trip tickets'
 'one-way tickets'
 'non-violent army'
 'black nationalists'
 'lyndon b. johnson'
 'democratic party'
 'civil rights'
 'moral stand\ufffd\ufffd\ufffdright'
 'election time'
 'thank']
['discourse on colonialism aime cesaire translated'
 'joan pinkham'
 'poetics of anticolonialism'
 'robin d. g. kelley'
 'introduction'
 'poetics of anticolonialism robin d. g. kelley aime cesaire'
 'discourse'
 'colonialism'
 'world manifesto'
 'old order bereft'
 'accompany manifestos'
 'discourse'
 'revolutionary ca.dences'
 'marx'
 'engels'
 'discours'
 'ie'
 'old empires'
 'world war'
 'europe'
 'philosophical shambles'
 'mrica'
 'asia'
 'america'
 'black people'
 'manchester'
 'england'
 'pan-mrican congress'
 'mrica'
 'non-aligned'
 'bandung'
 'indonesia'
 'mao'
 u"'s revolution"
 'china'
 'mau ma'
 'kenya'
 'colonial masters'
 'algeria'
 'tunisia'
 'morocco'
 'cameroon'
 'madagascar'
 'humiliating defeat'
 'viet minh'
 'dien bien ph'
 'revolt'
 'india'
 'philippines'
 'guyana'
 'egypt'
 'guatemala'
 'mrica'
 'alabama'
 'mississippi'
 'georgia'
 'harlem'
 'revolt'
 'malcolm x'
 'extraordinary moment'
 'long decade'
 'world war'
 'late 1950s'
 'tidal wave'
 'discourse'
 'colonialism'
 'key texts'
 'tidal wave'
 'anticolonial literature'
 'postwar period-works'
 'w.e.b'
 'bois'
 'color'
 'democrary'
 'worldandafrica'
 'frantz fanon'
 'black skin'
 'masks'
 'george padmore'
 'pan-africanism'
 'coming struggle'
 'africa'
 'albert memmi'
 'colonizer'
 'colonized'
 'richard wright'
 'white man'
 'listen'
 'jean-paul'
 u"'s essay"
 'black or.pheus'
 'presence africaine'
 'aftican revolution'
 'radical literature'
 'discourse'
 'colonial question front'
 'cesaire'
 'communist affiliation'
 'modern proletariat'
 'revolutionary force'
 'hegelian'
 'cesaire'
 'immorality constitute'
 'dead weight'
 'master class'
 'colonial power'
 'brutal violence'
 'end result'
 'europe'
 'hence'
 'europe'
 'europe'
 'anticipating fanon'
 'famous propo.sition'
 'europe'
 'cesaire'
 u"world 's civilizers"
 'mricans'
 'asians'
 'colonial encounter'
 'deliberate destruction'
 'cesaire'
 'discourse'
 'cesaire'
 u"'s discourse"
 'spiritual havoc'
 'colonial discourse'
 'anticipating'
 'postcolonial studies'
 'cesaire'
 u"'s critique"
 'dominique o. mannoni'
 'roger caillois'
 'ernest renan'
 'yves florenne'
 'jules romains'
 'colonial ideology-an ideology'
 'cultural hierarchy-is'
 'colonial rule'
 'corvee labor'
 'surprisingly'
 'postcolonial criticism pay'
 'discourse'
 'robert'
 u"young 's"
 'mythologies'
 'writing history'
 'postcolonial studies'
 'fanon'
 'wretched'
 'earth'
 'fanon'
 'discourse.3'
 'literary critics'
 'discourse'
 'cesaire'
 u"'s eleven-year stint"
 'communist party'
 'martinique'
 'marxist'
 'discourse'
 'critical contributions'
 'civilization'
 'cesaire'
 'marxism'
 'marxist'
 'discourse'
 'marx'
 'w.e.b'
 'bois'
 'm.n'
 'roy'
 'anticolonial struggle supersedes'
 'proletarian revolution'
 'fundamental historical movement'
 'capitalism versus socialism'
 'colonialist system'
 'whole new world'
 'final point'
 'discourse'
 'surrealist text'
 'cesaire'
 u"'s understanding"
 'rimbaud'
 'historical materialism'
 'marxist'
 'negri'
 'tudian assertion'
 'cesaire'
 u"'s text plumbs"
 u"'s uncon.scious"
 'red book'
 'pithy quotes'
 'dancing flame'
 'aime'
 u"cesaire 's credentials"
 'colonial critic'
 'june'
 'small town'
 'bassepointe'
 'martinique'
 'local tax inspector'
 'cultural sensibilities'
 'petit bourgeois'
 'cesaires'
 'rural poverty'
 'aime'
 'precocious student'
 'lycee schoelcher'
 'fort-de-france'
 'leon.gontran damas'
 'guiana'
 'childhood soccer-mates'
 'senegalese'
 'leopold sedar senghor'
 'negritude'
 'lycee'
 'french'
 'english'
 'mother country-france'
 'antillean'
 'paris'
 'paris'
 'lycee louis-ie-grand'
 'entrance exams'
 'ecole normale superieure'
 'senghor'
 'meeting senghor'
 'senegalese'
 'ousman soce'
 'cesaire'
 'mrica'
 'negritude'
 'black diasporic'
 'intellectual circles'
 'paris'
 'nardal'
 'martinique'
 'paulette'
 'jane'
 'andree'
 'revue'
 'du monde noir'
 'paulette nardal'
 'leo sajous'
 'martinican'
 'etienne lero'
 'rene menil'
 'j.m'
 'monnerot'
 'pierre'
 'simone yoyotte'
 'communist revolution'
 'legitime'
 'french-speaking'
 'black bourgeoisie'
 'west indian literature'
 'black u.s. writers'
 'langston hughes'
 'claude mckay'
 'special attention'
 'scottsboro'
 'cesaire'
 'nardal'
 'legitime'
 'french surrealists'
 'cesaire'
 'senghor'
 'leon damas'
 'different intellectual circle'
 u"l 'etudiant noir"
 'march'
 'cesaire'
 'passionate tract'
 'negritude'
 'cesaire'
 u"'s piece"
 'european humanities'
 'entrance exams'
 'ecole normale superieure'
 'emotional costs'
 'cesaire'
 'short vacation'
 'yugoslavia'
 'fellow student'
 'adriatic'
 'cesaire'
 'small island'
 'moved'
 'long poem'
 'martinique'
 'youth-the land'
 'martinska'
 'magical chance encounter'
 'moonlit night'
 'famous poem'
 'cahier'
 u"d'un retour au"
 'notebook'
 'return'
 'native land'
 'martinique'
 'france'
 'mrican-american'
 'harlem'
 'july'
 'suzanne roussy'
 'martinican'
 u"l 'etudiant noir.7"
 'martinique'
 'fort-de-france'
 'joining'
 'rene menil'
 'lucie thesee'
 'aristide maugee'
 'georges gratiant'
 'tropiques'
 'tropiques'
 'f ranee'
 'vichy'
 'martinique'
 'guadeloupe'
 'guiana'
 'vichy'
 'cesaire'
 'french broth.erhood'
 'french'
 'literary critic'
 'a. james arnold'
 'military regime'
 'martinicans'
 'official policy'
 'cesaire'
 'anticolonialist posture'
 'official policy'
 'tropiques'
 u"group 's radicalization"
 'notorious letter'
 'may'
 'martinique'
 u"'s chief"
 'information'
 'bayle'
 'tropiques'
 'revolutionary review'
 'bayle'
 'brilliant polemical response'
 'lieutenant'
 'vaisseau bayle'
 'sir'
 'tropiques'
 'racists'
 'poisoners'
 'souls'
 'good country'
 'zola'
 'revolutionaries'
 'hugo'
 'chatiments'
 'sectarians'
 'rimbaud'
 'lau.treamont'
 'racists'
 u"toussaint l'ouverture"
 'claude mckay'
 'langston hughes'
 'drumont'
 'hitler'
 'vain recriminations'
 'signed'
 'aime cesaire'
 'suzanne cesaire'
 'georges gratiant'
 'aristide'
 'maugee'
 'rene menil'
 'lucie thesee'
 'tropiques'
 'west indian folklore'
 'tropiques'
 'radical surrealist publications'
 'lasting'
 'rene menii'
 'sophisticated anticolonial stance'
 'theirs'
 'modernism'
 'deep appreciation'
 'african modes'
 'surrealism'
 'marxism'
 'productive forces'
 'negritude'
 'marxism'
 'collective efforts'
 'profound impact'
 'international surrealism'
 'andre breton'
 'tropiques'
 'breton'
 'pierre mabille'
 'benjamin peret'
 'suzanne cesaire'
 u"surrealism 's"
 'original theorists'
 'suzanne'
 'broader movements'
 'romanticism'
 'negritude'
 'surrealism'
 'permanent readiness'
 'marvelous'
 'tropiques'
 'new possibilities'
 'marxists'
 'certain inclinations'
 'marvelous'
 'colonial domina.tion'
 'everyday life'
 'martinique'
 'surrealism'
 'us'
 u"husband 's"
 'discourse'
 'colonialism'
 'tionary attitude'
 'surrealism strengthens'
 'impatient strength'
 'massive army'
 'millions'
 'black hands'
 'furious skies'
 'world war'
 'freed'
 'sordid dichotomies'
 'europeans/afri.cans'
 'magic power'
 'colonial idiocy'
 u"welder 's"
 'blue flame'
 'unprecedented communions'
 'aime cesaire'
 'andre breton'
 'cesaire'
 'surrealism'
 'marxism'
 'non-european traditions'
 'interpretation leaves'
 'cesaires'
 'aime'
 'suzanne'
 'fresh ideas'
 'breton'
 'cesaires'
 'paris'
 'new vistas'
 'marvelous'
 'aime cesaire'
 'surrealist leanings'
 'ab'
 'surrealism'
 'surrealism'
 'powerful unconscious forces'
 'mrica'
 'french'
 'cartesian'
 'french'
 'jacqueline leiner'
 'breton'
 u"'s role"
 'breton'
 'breton'
 'breton'
 'deputy m'
 'cesaire'
 'publish poetry'
 'surrealist publications'
 'surrealism'
 'exhibit catalogue'
 'andre breton'
 'marcel duchamp'
 'surrealist imagery'
 'poetry collections'
 'les armes'
 'miraculous weapons'
 'solei'
 'cou coupe'
 'beheaded sun'
 'cesaire'
 u"'s essay"
 'poetry'
 'cognition'
 'haiti'
 'tropiques'
 'systematic statements'
 'revolutionary nature'
 'opening'
 'provocative proposition'
 'poetic'
 'great silence'
 'scientific knowledge'
 u"world 's crises"
 'cesaire'
 u"'s embrace"
 'discourse'
 'discourse'
 'historical prose poem'
 'cesaire'
 'lucid intelligence'
 'sharpest sensibility'
 'subtlest feelings'
 'life form'
 'creative im.pulse-is'
 'powerful source'
 'discourse'
 u"'s sharpest weapon"
 'war drums'
 'powerful sections'
 'systematic critique replete'
 'sufficient evidence'
 'topic sentences'
 'bullet points'
 'con.sider cesaire'
 'poetic knowledge'
 'poetic'
 'man spatters'
 'surrealism'
 'discourse'
 'pan-mricanism'
 'negritude'
 'own independent anticolonial roots'
 'cesaire'
 u"'s critique"
 'mutual attraction'
 'cesaire'
 'black intellectuals'
 'up'
 'euro.pean'
 'cultural iconoclasts'
 'radical pronouncements'
 'social revolution'
 'paris surrealist'
 'french communist party'
 'abd-el-krim'
 'rif'
 'french'
 'morocco'
 'french'
 'colonial rule'
 'letter'
 'paul claudel'
 'japan'
 'paris'
 'colonial insurrections'
 'western civilization'
 'orient'
 'paris'
 'militant statement'
 'colonial question'
 'titled'
 'murderous humanitarianism'
 'rene crevel'
 'andre breton'
 'paul eluard'
 'benjamin peret'
 'yves tanguy'
 'martinican'
 'pierre yoyotte'
 'monnerot'
 'relentless attack'
 'black bourgeoisie'
 'hypocritical liberals'
 'surrealists'
 'imperialist war'
 'colonial form'
 'civil war'
 'colonial problem'
 'color question'
 'murderous humanitarianism'
 'cesaire'
 u"'s critique"
 'european proletariat'
 'more.over'
 'world war'
 'discourse'
 'direct link'
 'cesaire'
 'europeans'
 'nazism'
 'non-european peoples'
 'nazism'
 'whole edifice'
 'christian civilization'
 'real crime'
 'white people'
 'colonial procedures'
 'arabs'
 'algeria'
 'mrica'
 'situate cesaire'
 'radical black intellectuals'
 'discourse'
 'cedric robinson'
 'radical black intellectuals'
 'w.e.b'
 'bois'
 'c.l.r james'
 'george padmore'
 'oliver cox'
 'logical development'
 'civilization'
 'global systems'
 'political economy'
 'racist ideologies'
 'ralph bunche'
 'radical political science professor'
 'howard'
 'imperialism birth'
 'fascisin'
 'bunche'
 'extreme jingoism'
 'comic-opera glorification'
 'world imperialism'
 'ruthless exploitation'
 'darker populations'
 'bois'
 'clearest statements'
 'hitler'
 'mussolini'
 'race prejudice'
 'white people'
 'britain'
 'france'
 'nazis'
 'africa'
 'nazi'
 'atrocity-concentration camps'
 'mur- der'
 'ghastly blasphemy'
 'christian civilization'
 'europe'
 'superior race'
 'superior race'
 'discourse'
 'negrirude'
 u"'s impulse"
 'mrica'
 u"'s accomplish.ments"
 'takirig'
 'leo frobenius'
 u"'s injunction"
 'negro'
 'european invention'
 'cesaire'
 'colonial mission'
 'smoke screen'
 'colonialism results'
 'massive destruction'
 'whole societies-societies'
 'high level'
 'valuable lessons'
 'modern world'
 u"cesaire 's insistence"
 'mrican'
 'asian cultures'
 'ante-capitalist ...'
 'romantic claims'
 'african nationalist leaders'
 'julius nyerere'
 'kenneth kaunda'
 'senghor'
 'africa'
 'pre-colonial village life'
 'discourse'
 'cesaire'
 'intro.duction'
 'victor schoelcher'
 'esclavage'
 'erect cities'
 'cultivate fields'
 'weave cotton'
 'forge steel'
 'own beauty'
 'mystical connections'
 'mutual assistance'
 'free accep'
 'order-earnestness-poetry'
 'free'
 'reading'
 'cesaire'
 u"'s brightest students"
 'frantz fanon'
 'africa'
 'black skin'
 'masks'
 'valid historical place'
 'white man'
 'negritude'
 'miraculous weapon'
 'negro'
 'cedric robinson'
 'black marxism'
 'making'
 'black radical tradition'
 'easy task'
 'negro'
 'racial boundary'
 'immense expenditures'
 'intellectual energies'
 'entire generation'
 'european scholars'
 'intellecrual contributions'
 'egypt'
 'nubia'
 'european history'
 'africa'
 'whole continent'
 'brutish heathens'
 'europe'
 'pure entity'
 'negro'
 'cesaire'
 u"'s construction"
 'africa'
 'communal societies'
 'old friend'
 'senghor'
 'cesaire'
 u"'s concept"
 'negritude'
 'discourse'
 'sterile attempt'
 'dead society'
 'exoticism .. ..'
 'new society'
 'brother slaves'
 'productive power'
 'modern times'
 'olden days'
 'soviet union'
 'cesaire'
 'communist party'
 'martinique'
 'communist ticket'
 'fort-de-france'
 'french national assembly'
 'stalinism'
 'circa 1950s'
 'new society'
 'great poet'
 'major voice'
 'negritude'
 'communist party'
 'postwar world'
 'communist parties worldwide'
 'europe'
 'joe stalin'
 'war years'
 'liberal democracy'
 'caribbean'
 'america'
 'cesaire'
 u"'s friends"
 'jacques romain'
 'nicolas guillen'
 'rene depestre'
 'cesaire'
 'cesaire'
 'martinique'
 'guadeloupe'
 'guiana'
 'reunion'
 'french republic'
 'departmentaliza.tion'
 'france'
 u"cesaire 's eloquent"
 'pas.sionate arguments'
 'old colonies'
 'equal rights'
 'pipe dream'
 'french officials'
 'martini.can'
 'discourse'
 'outspoken critic'
 'departmenta lzatlon ..'
 'i\ufffd'
 u"cesaire 's role"
 'communist leader'
 u"discourse'snod"
 'soviet union'
 'names proletarian revolution'
 'europe'
 'colonial violence'
 'silent complicity'
 'proletarian revolution'
 'final solution'
 'fanon'
 'europe'
 'european bourgeoisie'
 'discourse'
 'marxism'
 'anti-rationalist ideas'
 'cesaire'
 'early poetry'
 'negritude'
 'new spiritual values'
 'cesaire'
 u"'s position vis-a.-vis"
 'marxism'
 'discourse'
 'october'
 'cesaire'
 'famous letter'
 'maurice thorez'
 'french communist party'
 'stalinism'
 'colonial question-not'
 u"party 's policies"
 'colonial relationship berween'
 'martinican'
 'parties'
 'arguing'
 'color need'
 'colonial question ...'
 'subsidiary part'
 'important global matter'
 'racism'
 'class struggle'
 'direct assertion'
 'world unity'
 'dis.course'
 'marxist'
 'communist party'
 'west indian islands'
 'africa'
 u"'s child"
 'chill abstractions'
 'cesaire'
 u"'s investment"
 'third-world revolt'
 'new society'
 'fanon'
 'europe'
 'old humanism'
 'europe'
 'cesaire'
 u"''i 'm"
 'narrow particularism'
 'universalism ...'
 'different idea'
 'cesaire'
 'discourse'
 'thorez'
 'african intellectual circles'
 'pervasive spirit'
 'negritude'
 'simple matter'
 'racial essentialism'
 'critic'
 'manthia diawara'
 'radical critiques'
 'colonial order'
 'discourse'
 'colonialism'
 'new generation'
 'negritude'
 'africa'
 'international moment'
 'universal emanci.pation'
 'universal freedom'
 'people worldwide-all'
 'important identity'
 'new historical mission'
 'archaic identities'
 'religious entrap.ments'
 'french'
 'recent events-genocide'
 'africa'
 'cuba'
 'progressive movements'
 'cesaire'
 'fanon'
 u"'s predictions"
 'colonial language'
 'cesaire critiques'
 'formal sense'
 'colonial state'
 'old colonial state'
 'primary difference'
 'black faces'
 'new ruling class-the class'
 'fanon'
 'colonial masters'
 'new jack u.s.'
 'corporate rulers'
 'stalinists'
 'colonial discourse'
 'cesaire'
 'true radicals'
 'postcolonial theoty'
 'official apparatus'
 'cultural links'
 'colonial domination'
 'discourse'
 'political economy'
 'colonial domination'
 'whole way'
 'european terms'
 'discourse'
 u"master class 's ideology"
 'fanon'
 'cesaire'
 'europe'
 u"'s footsteps"
 'ancient way'
 'new direction altogether'
 'cesaire'
 'martinique'
 'fort-de.france'
 'brief pages'
 'old political parties'
 'labor exploitation'
 'different way'
 'discourse'
 'road map'
 'cesaire'
 'own miraculous weapons'
 'tropiques'
 'vichy'
 'european culture'
 'france'
 'native land'
 'revolutionary graffiti'
 'bold strokes'
 'great texts'
 'civilization'
 'hand grenade'
 'new history'
 'discourse'
 'dead docu.ment'
 'dead order'
 'different way'
 'cesaire'
 'lautn'
 u"amont 's"
 'chants'
 'maldoror'
 'can.nibalistic nature'
 'poetic knowledge'
 'discourse'
 'new insights'
 'postcolonial predicament'
 'old colonial order'
 'malcolm x'
 'ballot'
 'bullet'
 'speech'
 'april'
 'malcolm x'
 'prominent members'
 'civil rights movement'
 'cory'
 'methodist church'
 'cleveland'
 'ohio'
 'april'
 'black populace'
 'important time'
 'malcolm x'
 u"'s life"
 'nation'
 'islam'
 'negro revolt'
 'humble way'
 'democrat'
 'republican'
 'hunkies'
 'polacks'
 'italian refugees'
 'europe'
 'well'
 'america'
 u"n't need"
 u"n't need"
 'washington'
 'd.c.'
 'civil-rights legislation'
 'polack'
 'black people'
 'americanism'
 'black people'
 'i.'
 'american dream system'
 'america'
 'american dream'
 'american nightmare'
 'new friends'
 'new allies'
 'civil-rights struggle'
 'human rights'
 'whenever'
 'civil-rights struggle'
 'uncle sam'
 'outside world'
 'civil-rights struggle'
 'civil rights'
 'domestic affairs'
 'african brothers'
 'asian brothers'
 'latin-american'
 'domestic affairs'
 'civil rights'
 'uncle sam'
 'human rights'
 'human rights'
 'africa'
 'hungary'
 'asia'
 'america'
 'negro'
 'human rights'
 'civil rights'
 'civil-rights tree'
 'human-rights tree'
 'civil-rights struggle'
 'human rights'
 'black man'
 'general assembly'
 'uncle sam'
 'world court'
 'human rights'
 'civil rights'
 'civil rights'
 'civil rights means'
 'uncle sam'
 'human rights'
 'human rights'
 'world court'
 'uncle sam'
 u"'s hands"
 'black man'
 u"earth 's number-one hypocrite"
 'free world'
 'free world'
 'shall overcome'
 'expand'
 'civil-rights struggle'
 'human rights'
 'african brothers'
 'latin-american'
 'chinamen'
 'washington'
 'd.c.'
 'political chicanery'
 'america'
 'tin soldier'
 'uncle sam'
 'know\ufffd\ufffd\ufffdi disagree'
 'lomax'
 'poor nations'
 'poor nations'
 'rich nations'
 'nation\ufffd\ufffd\ufffdone vote'
 'equal vote'
 'asia'
 'africa'
 'darker parts'
 'sam'
 'russia'
 'right'
 'african-americans\ufffd\ufffd\ufffdthat'
 'america'
 'africans'
 'africans'
 'negro'
 'africans'
 u"n't catch hell"
 'civil-rights bills'
 'africans'
 'negro'
 'hoogagagooba'
 u"'ll show"
 'white man'
 'silly man'
 'atlanta'
 'white restaurant'
 'negro'
 'nigger dare'
 'muslim mosque'
 'york'
 'muslims'
 'islam'
 u"n't mix"
 'civil activities\ufffd\ufffd\ufffdnot'
 'religious services'
 'muslims'
 'political action'
 'economic action'
 'civic action'
 'social evils'
 'political philosophy'
 'black nationalism'
 'black man'
 'own community'
 'black man'
 'black community'
 'political philosophy'
 'black nationalism'
 'christian church'
 'naacp'
 'core'
 'sncc'
 '[ student'
 'nonviolent coordinating'
 'committee ] meetings'
 'muslim'
 'black'
 'shall overcome'
 'economic philosophy'
 'black nationalism'
 'white people'
 'white people'
 'white man'
 u"black man ca n't"
 'white community'
 'white man'
 'black community'
 'black nationalism involves'
 're-education program'
 'black community'
 'slum area'
 'white man'
 'economic philosophy'
 'black nationalism'
 'civic organization'
 'fraternal order'
 u"'s time"
 'own community'
 'own kind'
 'gain control'
 'own community'
 'social philosophy'
 'black nationalism'
 'drug addiction'
 'moral fiber'
 'own society'
 'own social circles'
 u"wo n't"
 'social circle'
 'great controversy'
 u"'s time"
 'article'
 'constitutional amendments'
 'white folks'
 'white man'
 'black man buying rifles'
 'white man'
 'malcolm'
 'uncle tom'
 'amen'
 'tom'
 'rifle clubs'
 'defense budget'
 u"ca n't begrudge"
 'medals'
 'big\ufffd\ufffd\ufffdany time'
 'cold blood'
 'white man'
 u"ca n't"
 'eichmann'
 'argentina'
 'american soldiers'
 u"'s business way"
 'vietnam'
 'cuba'
 'free elections'
 'old cracker'
 'free elections'
 'own country'
 'negro'
 'cracker senator'
 'black people'
 'washington'
 'shall overcome'
 'white friends'
 'round-trip tickets'
 'one-way tickets'
 'non-violent army'
 'black nationalists'
 'lyndon b. johnson'
 'democratic party'
 'civil rights'
 'moral stand'
 'election time'
 'thank']
